#!/bin/sh

source /etc/rtsp/config.txt

while true; do
	if pidof snx_rtsp_server >/dev/null; then
		continue
	else
		LD_LIBRARY_PATH=/etc/rtsp /etc/rtsp/snx_rtsp_server ${SNXRTSPSERVERARGS} >/dev/null &
	fi
done;
